default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: carb_tracker_development

test:
  <<: *default
  database: carb_tracker_test

production:
  <<: *default
  database: carb_tracker_production
  username: carb_tracker
  password: <%= ENV['CARB_TRACKER_DATABASE_PASSWORD'] %>
  url:  <%= ENV["DATABASE_URL"] %>

